title: Zecheng Gan
# logo: /assets/img/logo.png
description: Homepage of Zecheng Gan （干则成）
show_downloads: true
google_analytics: UA-130614145-1
theme: jekyll-theme-minimal
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one